name: Test
on:
  workflow_dispatch:
    inputs:
      test_var:
        description: Run only Liquibase plan
        type: boolean
        required: false
        default: false
      dry_run:
        description: Run only Liquibase plan
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  create_rfc:
    name: Create RFC
    runs-on: ubuntu-latest
    steps:
      - name: RFC
        run: |-
          echo ${{ inputs.dry_run }}
          echo ${{ inputs.test_var }}
